[project]
name = "infra"
version = "1.0.4"
requires-python = ">=3.12,<3.14"
dependencies = [
  "boto>=2.49.0",
  "pulumi>=3.213.0",
  "pulumi-aws>=6.83.2",
  "pytest>=8.3.5",
  "pytest-asyncio>=1.3.0"
]

[tool.uv.workspace]
members = [
  "components",
]
