[project]
name = "infra"
version = "1.0.5"
requires-python = ">=3.12,<3.14"
dependencies = []

[dependency-groups]
dev = ["pre-commit>=4.5.1", "uv>=0.9.2"]

[tool.uv.workspace]
members = ["components", "policies"]
