name: Pull request

on:
  pull_request:
    types: [labeled, opened, synchronize]

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge-release-notes-pr:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.pull_request.labels.*.name, 'autorelease: pending')
    steps:
      - uses: actions/checkout@v5
      - run: gh pr merge ${{ github.event.pull_request.number }} --squash
        env:
          GITHUB_TOKEN: ${{ secrets.INFRA_REPO_TOKEN }}
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        working-directory: [components]
    defaults:
      run:
        working-directory: ${{ matrix.working-directory }}
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v7
      - uses: extractions/setup-just@v3
      - run: just test
